stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

unit-test-app:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image:  gradle:7.1.0-jdk11
  script:
    - cd TourGuideApp && chmod +x gradlew && ./gradlew test

build-app:       # This job runs in the build stage, which runs first.
  stage: build
  image:  gradle:7.1.0-jdk11
  script:
    - cd TourGuideApp
    - docker build . -t test
    - docker tag  bintou01/tour_guide_app:test
    - docker push bintou01/tour_guide_app:test
  only:
    - master

#deploy-app:      # This job runs in the deploy stage.
#  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#  script:
#    - cd TourGuideApp
#  only:
#    - master
