version: '3.7'
services:
  gps:
    container_name: gps
    build:
      context: gps
      dockerfile: Dockerfile
    image: tour_guide_app
    ports:
      - 8081:8081
    networks:
      - spring-cloud-network
  tripPricer:
    container_name: tripPricer
    build:
      context: tripPricer
      dockerfile: Dockerfile
    image: tour_guide_app
    ports:
      - 8083:8083
    networks:
      - spring-cloud-network
  rewardsCentral:
    container_name: rewardsCentral
    build:
      context: rewardsCentral
      dockerfile: Dockerfile
    image: tour_guide_app
    ports:
      - 8082:8082
    networks:
      - spring-cloud-network
  guide-project:
    container_name: guide-project
    build:
      context: guide-project
      dockerfile: Dockerfile
    image: tour_guide_app
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge
